name: SpleefArena
version: ${project.version}
main: me.giodev.spleefarena.SpleefArena
api-version: 1.16
depend: [WorldGuard,WorldEdit]
commands:
  spleefarena:
    aliases: ["sa"]
    usage: "/sa <args>"
    description: "SpleefArenas's main command"